name: CI/CD

on:
  push:
    branches: [ '**' ]
    tags:
      - 'v*'
  pull_request:
    branches: [ '**' ]

jobs:
  test-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test

  test-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Compile extension
        run: npm run compile

  release:
    needs: [test-dart, test-extension]
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          dart pub get

      - name: Package Extension
        run: npx @vscode/vsce package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
